### ISSUE TITLE
Build fails often with generic error

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-open-scd#113]
A lot of times the build fails at the following point, but a retry often works.
So it doesn't seem to be a problem in the test, but more a build process issue

Example of the error:
test/unit/menu/UpdateDescriptionSEL.test.ts:

 🚧 404 network requests:
    - compas-scl-data-service/common/v1/userinfo
    - src/menu/CompasOpen.js
    - src/menu/NewProject.js
    - src/menu/CompasCimMapping.js
    - src/menu/CompasSave.js
    - src/validators/ValidateSchema.js
    - src/validators/ValidateTemplates.js
    - src/menu/CompasImportIEDs.js
    - src/menu/SubscriberInfo.js
    - src/menu/CompasMerge.js
    - src/menu/CompasUpdateSubstation.js
    - src/menu/CompasAutoAlignment.js
    - src/menu/CompasSettings.js
    - src/menu/Help.js

 ❌ Error: Uncaught TypeError: Cannot read properties of null (reading 'open') (http://localhost:8000/src/Logging.ts:153) 
      at createLogEvent (src/compas-services/foundation.ts:78:22)
      at src/compas/CompasSession.ts:225:6
      at async retrieveUserInfo (src/compas/CompasSession.ts:213:2)

**Comment by dlabordus** [comment]
Temporary solution is to make the CoMPAS Settings plugin start the UserInfo retrieval. This way test are less impacted.
