### ISSUE TITLE
Build fails (sometimes) with error in file 'reportcontrol.test.ts'

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-open-scd#206]
**Describe the bug**
Sometimes the build fails with the following error:

```
test/unit/wizards/reportcontrol.test.ts:

 ❌ Wizards for SCL ReportControl element > define an edit wizard that > for complete ReportControl element > rejects intgPd attribute starting with not being a unsigned int
      Error: Property failed after 81 tests
      { seed: 486084177, path: "80:2", endOnFailure: true }
      Counterexample: ["-0"]
      Shrunk 1 time(s)
      Got error: AssertionError: expected true to be false
      
      Stack trace: AssertionError: expected true to be false
          at http://localhost:8000/test/unit/wizards/reportcontrol.test.ts?wtr-session-id=KMsQCXsTcWqxuzqw_Rjlw:89:46
          at async AsyncProperty.run (http://localhost:8000/node_modules/fast-check/lib/esm/check/property/AsyncProperty.generic.js:38:28)
          at async asyncRunIt (http://localhost:8000/node_modules/fast-check/lib/esm/check/runner/Runner.js:21:21)
          at async qy.<anonymous> (http://localhost:8000/test/unit/wizards/reportcontrol.test.ts?wtr-session-id=KMsQCXsTcWqxuzqw_Rjlw:86:9)
      
      Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
        at test/unit/wizards/reportcontrol.test.ts:147:48
        at async AsyncProperty.run (node_modules/fast-check/lib/esm/check/property/AsyncProperty.generic.js:38:28)
        at async asyncRunIt (node_modules/fast-check/lib/esm/check/runner/Runner.js:21:21)
        at async qy.<anonymous> (test/unit/wizards/reportcontrol.test.ts:143:8)
        Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
        at asyncThrowIfFailed (node_modules/fast-check/lib/esm/check/runner/utils/RunDetailsFormatter.js:128:11)
```

Restarting the job will most of the time be successful. 

**Expected behavior**
Build should not fai;l :-)

**Additional context**
This probably needs to be fixed in the upstream OpenSCD.

**Comment by dlabordus** [comment]
Also have a lot of these errors

```
❌ open-scd > looks like its snapshot
      AssertionError: Snapshot open-scd looks like its snapshot does not match the saved snapshot on disk
      + expected - actual
      
         <mwc-list
           id="content"
           wrapfocus=""
         >
      -    <abbr title="Error communicating with CoMPAS Ecosystem">
      -      <mwc-list-item
      -        aria-disabled="false"
      -        class="error"
      -        graphic="icon"
      -        mwc-list-item=""
      -        tabindex="-1"
      -        twoline=""
      -      >
      -        <span>
      -          <tt>
      -            11/24/2022, 11:53:50 AM
      -          </tt>
      -          Error communicating with CoMPAS Ecosystem
      -        </span>
      -        <span slot="secondary">
      -          NotFoundError: Not Found (404)
      -        </span>
      -        <mwc-icon
      -          slot="graphic"
      -          style="--mdc-theme-text-icon-on-background:var(--red)"
      -        >
      -          report
      -        </mwc-icon>
      -      </mwc-list-item>
      -    </abbr>
      -    <abbr title="Error communicating with CoMPAS Ecosystem">
      -      <mwc-list-item
      -        aria-disabled="false"
      -        class="error"
      -        graphic="icon"
      -        mwc-list-item=""
      -        tabindex="-1"
      -        twoline=""
      -      >
      -        <span>
      -          <tt>
      -            11/24/2022, 11:53:50 AM
      -          </tt>
      -          Error communicating with CoMPAS Ecosystem
      -        </span>
      -        <span slot="secondary">
      -          NotFoundError: Not Found ([404](https://github.com/com-pas/compas-open-scd/actions/runs/3540145116/jobs/5943145278#step:7:405))
      -        </span>
      -        <mwc-icon
      -          slot="graphic"
      -          style="--mdc-theme-text-icon-on-background:var(--red)"
      -        >
      -          report
      -        </mwc-icon>
      -      </mwc-list-item>
      -    </abbr>
      +    <mwc-list-item
      +      aria-disabled="true"
      +      disabled=""
      +      graphic="icon"
      +      mwc-list-item=""
      +      tabindex="0"
      +    >
      +      <span>
      +        Edits, errors, and other notifications will show up here.
      +      </span>
      +      <mwc-icon slot="graphic">
      +        info
      +      </mwc-icon>
      +    </mwc-list-item>
         </mwc-list>
         <mwc-button
           disabled=""
           icon="undo"
         </mwc-icon-button>
       </mwc-snackbar>
       <mwc-snackbar
         id="error"
      -  labeltext="Error communicating with CoMPAS Ecosystem"
      -  open=""
      +  labeltext="No errors"
         timeoutms="10000"
       >
         <mwc-button
           icon="history"
```
